
POST http://localhost:3000/api/links
Content-Type: application/json

{
    "code": "linkedin",
    "url": "https://www.linkedin.com/feed/"
}

###
GET http://localhost:3000/api/links

###
GET http://localhost:3000/rodolphoreis
